-- MySQL Script generated by MySQL Workbench
-- 11/05/14 20:36:40
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jarvis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jarvis` ;
CREATE SCHEMA IF NOT EXISTS `jarvis` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `jarvis` ;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `token` VARCHAR(500) NULL,
  `date_create` DATETIME NULL,
  `date_last_connection` DATETIME NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `age` VARCHAR(100) NULL,
  `sexe` VARCHAR(100) NULL,
  `admin` VARCHAR(100) NULL,
  `url_image_profil` VARCHAR(100) NULL,
  `description` VARCHAR(999) NULL,
  `regId` VARCHAR(1200) NULL,
  `version_jarvis` VARCHAR(45) NULL,
  `version_android` VARCHAR(60) NULL,
  `language` VARCHAR(50) NULL,
  `longitude` VARCHAR(80) NULL,
  `latitude` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `File` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `File` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NULL,
  `size` BIGINT NULL,
  `visibility` VARCHAR(100) NULL,
  `date_create` DATETIME NULL,
  `id_User` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
